### PR TITLE
add screen to apt all, update forever script with correct path

### PR DESCRIPTION
**Pull request by mrjones-plip**
this pr:
* adds `screen` to the `apt install` call as we use in the bash script
* updates the `forever.sh` to use the same directory name as the repo so that it works ;)

### CODE REVIEW

**Comment by mrjones-plip** [comment]
gotcha! is preferred dev flow 3rd party branch -> `develop` branch -> `main` branch?

will follow that for future PRs

**Comment by NegativeK** [comment]
Preferred flow, yeah. To keep my super critical not critical at all pi camera up to date with main while we do changes.

**Comment by mrjones-plip** [comment]
sounds good! i'll target `develop` from now on.  As well, I've re-parented this branch to target `develop` instead of `main`.

While I agree it's a bit silly to have the overhead of [SemVer](https://en.wikipedia.org/wiki/Software_versioning#Semantic_versioning) so early in a project, I've always liked that as you can then easily have `main` be ahead of, say, version `1.0.0` which you have running stable and static in production.  Don't cut a version until it's ready!  This also can eventually lead to [CD](https://en.wikipedia.org/wiki/Continuous_delivery) on a per commit basis (again WAY overkill, I know) . For an example of what this looks like, I helped set it up on [this project](https://github.com/medic/cht-watchdog) (see `.github` dir for the [meat](https://github.com/medic/cht-watchdog/tree/main/.github/workflows)).

**Comment by NegativeK** [comment]
Oh man, commit to main versus git flow...

**Pull request merged**
